namespace: longhorn-system

# Default job concurrency
defaultConcurrency: 4

# Optionally create storageclasses for each group
# This is disabled by default because the Helm release will fail if
# An upgrade is run and it tries to remove an in-use StorageClass
createStorageClasses: false

# Default StorageClass properties
defaultAllowVolumeExpansion: true
defaultReclaimPolicy: Retain
defaultReplicaAutoBalance: "disabled"
defaultNumberOfReplicas: "3"
defaultStaleReplicaTimeout: "2880"

# group names must start and end with alnum, and can only have [A-Za-z0-9\-_.] or [A-Za-z0-9\-] if creating StorageClasses
groups:
  "Blog":
    # allowVolumeExpansion: true
    # reclaimPolicy: Delete
    # replicaAutoBalance: "best-effort"
    # numberOfReplicas: "2"
    # staleReplicaTimeout: "30"
    snapshot:
      - interval: 10m
        retain: 6
        # concurrency: 10
    backup: 
      - interval: 1h
        retain: 5
      - interval: 6h
        retain: 4
