namespace: longhorn-system

defaultConcurrency: 4

# group names must start and end with alnum, and can only have [A-Za-z0-9-_.]
groups:
  "Database":
    snapshot:
      # interval can end in 'h', 'm', or 'd'
      - interval: 10m
        retain: 6
    backup:
      - interval: 1h
        retain: 6
      - interval: 6h
        retain: 8
