# -- Number of replicas
replicaCount: 1

# -- Array of devices
# @default -- See values.yaml for an example
devices: []
  # - name: localhost
  #   address: 127.0.0.1

image:
  # -- Image repository
  repository: zibby/tplink-exporter
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag
  tag: "latest"

# -- Image pull secrets (example: `[{"name": "secretname"}]`)
imagePullSecrets: []

# -- Pod annotations
podAnnotations: {}

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8089

# -- Resource requests and limits
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
