repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        description: Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
        language: script
        entry: .pre-commit/helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
