{{- if eq "" .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neko.name" . }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value | b64enc }}"
  {{- end }}
{{- end }}