apiVersion: v1
kind: Service
metadata:
  name: {{ include "neko.name" . }}
  labels:
    {{- include "neko.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- with .Values.env.NEKO_UDPMUX }}
    - name: udpmux
      port: {{ .}}
      targetPort: {{ . }}
      protocol: UDP
  {{- end }}
  {{- with .Values.env.NEKO_TCPMUX }}
    - name: tcpmux
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "neko.selectorLabels" . | nindent 4 }}
{{- if .Values.env.NEKO_EPR }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neko.name" . }}-udp
  labels:
    {{- include "neko.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq "LoadBalancer" .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    {{- $start := atoi (regexFind "[0-9]+" .Values.env.NEKO_EPR) -}}
    {{- $end := atoi (trimPrefix "-" (regexFind "-[0-9]+" .Values.env.NEKO_EPR)) -}}
    {{- range $port := untilStep $start $end 1 }}
      - name: udp{{ $port }}
        port: {{ $port }}
        targetPort: {{ $port }}
        protocol: UDP
    {{- end }}
  selector:
    {{- include "neko.selectorLabels" . | nindent 4 }}
{{- end }}