{{- /* Storage Classes */}}
{{- if .Values.createStorageClasses -}}
{{- range $group, $property := .Values.groups -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-{{ lower $group }}
provisioner: driver.longhorn.io
allowVolumeExpansion: {{ ((($property).options).storageclass).allowVolumeExpansion | default ((($.Values)).storageclass).allowVolumeExpansion }}
reclaimPolicy: "{{ ((($property).options).storageclass).reclaimPolicy | default $.Values.storageclass.reclaimPolicy }}"
parameters:
{{- /* Set parameters if they're specified at the top level OR for this specific group */}}
{{- if or (hasKey $.Values "parameters") (hasKey $property "options.parameters") -}}
  {{- $parameters := mergeOverwrite dict ((($.Values)).parameters | default dict) ((($property).options).parameters | default dict) -}}
  {{- range $key, $value := $parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end -}}
{{ end }}
  recurringJobSelector: "[{\"name\":\"{{ $group }}\",\"isGroup\":true}]"
---
{{ end }}
{{- end -}}
