service:
  annotations:
    metallb.universe.tf/allow-shared-ip: media-neko
  type: LoadBalancer
  loadBalancerIP: 192.168.1.74
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: neko.tyzbit.io
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: neko.tyzbit.io-tls
     hosts:
       - neko.tyzbit.io