{{ $pvcName := include "grav.fullname" . }}
{{- if ne .Values.persistence.existingClaimName "" }}
  {{ $pvcName = .Values.persistence.existingClaimName }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grav.fullname" . }}
  labels:
    {{- include "grav.labels" . | nindent 4 }}
  {{ with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grav.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.grav.image.repository }}:{{ .Values.grav.image.tag }}"
          imagePullPolicy: {{ .Values.grav.image.pullPolicy }}
          {{- if .Values.grav.config }}
          env: 
          {{- range $env, $value := .Values.grav.config }}
            - name: {{ $env }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.grav.probes.enabled }}
          startupProbe:
            initialDelaySeconds: {{ .Values.grav.probes.startup.initialDelaySeconds }}
            failureThreshold: {{ .Values.grav.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.grav.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.grav.probes.startup.timeoutSeconds }}
            httpGet:
              path: /
              port: http
          livenessProbe:
            initialDelaySeconds: {{ .Values.grav.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.grav.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.grav.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.grav.probes.liveness.timeoutSeconds }}
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.grav.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.grav.probes.readiness.failureThreshold }}
            periodSeconds: {{ .Values.grav.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.grav.probes.readiness.timeoutSeconds }}
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.grav.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/www/grav/backup
              subPath: backup
              name: {{ $pvcName }}
            - mountPath: /var/www/grav/logs
              subPath: logs
              name: {{ $pvcName }}
            - mountPath: /var/www/grav/user
              subPath: user
              name: {{ $pvcName }}
            - mountPath: /etc/php/7.4/fpm/conf.d/99-custom.ini
              subPath: 99-custom.ini
              name: custom-ini
            - mountPath: /var/www/grav/user/config/scheduler.yaml
              subPath: scheduler.yaml
              name: scheduler
      volumes:
        - name: {{ $pvcName }}
          persistentVolumeClaim:
            claimName: {{ $pvcName }}
        - name: custom-ini
          configMap:
            name: {{ include "grav.fullname" . }}-custom-ini
        - name: scheduler
          configMap:
            name: {{ include "grav.fullname" . }}-scheduler
      {{- with .Values.grav.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grav.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grav.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}