{{ $pvcName := include "grav.fullname" . }}
{{- if ne .Values.persistence.existingClaimName "" }}
  {{ $pvcName = .Values.persistence.existingClaimName }}
{{- end }}
{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "grav.fullname" . }}-filebrowser
  labels:
    {{- include "grav.labels" . | nindent 4 }}
  {{ with .Values.statefulSetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "grav.fullname" . }}-filebrowser
  selector:
    matchLabels:
      {{- include "filebrowser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filebrowser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-filebrowser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.filebrowser.image.repository }}:{{ .Values.filebrowser.image.tag }}"
          imagePullPolicy: {{ .Values.filebrowser.image.pullPolicy }}
          args:
            {{- toYaml .Values.filebrowser.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.filebrowser.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ $pvcName }}
              subPath: filebrowser
              mountPath: /db
            - mountPath: "/srv/backup"
              subPath: backup
              name: {{ $pvcName }}
            - mountPath: "/srv/logs"
              subPath: logs
              name: {{ $pvcName }}
            - mountPath: "/srv/user"
              subPath: user
              name: {{ $pvcName }}
      volumes:
        - name: {{ $pvcName }}
          persistentVolumeClaim:
            claimName: {{ $pvcName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}