apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inspector-configs
  namespace: {{ .Values.namespace }}
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: {{ .Values.storageClassName | default "nfs-client" }}
  resources:
    requests:
      storage: 1Gi